// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGd_i4BwTpqc71_BJne6pk77U7ygl6QdY',
    appId: '1:463933262309:web:b8219e966e7ef562ba070c',
    messagingSenderId: '463933262309',
    projectId: 'chat-app-e8c64',
    authDomain: 'chat-app-e8c64.firebaseapp.com',
    storageBucket: 'chat-app-e8c64.appspot.com',
    measurementId: 'G-Z0XL2P0B30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28bXXRQjSbFaXnTAfXM8ZuuLGlGmCsj0',
    appId: '1:463933262309:android:7e15f9df2e7573daba070c',
    messagingSenderId: '463933262309',
    projectId: 'chat-app-e8c64',
    storageBucket: 'chat-app-e8c64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDKM6aOmq2b5o0Y01vptwqyknJJBDF5Ns',
    appId: '1:463933262309:ios:35e7faf8826b90d0ba070c',
    messagingSenderId: '463933262309',
    projectId: 'chat-app-e8c64',
    storageBucket: 'chat-app-e8c64.appspot.com',
    iosClientId: '463933262309-2jj61i196voki9jsktfvbb348g4h7pio.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
